AllCops:
  NewCops: enable
  UseCache: true
  CacheRootDirectory: tmp/cache/rubocop

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 75

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 300
